### ISSUE TITLE
Port to new osmium version

### ISSUE THREAD

**Issue by RockLobster** [MaZderMind/osm-history-splitter#13]
Hi there :)

Are there any plans on porting the code from the ancient osmium version to the maintained one?

**Comment by MaZderMind** [comment]
Thank you very much for volunteering ;)
Fun aside: No, I don't have plans to do so but I'll leave this issue open so people are aware that this is something that should be done. I'm happy to merge PRs :)

**Comment by RockLobster** [comment]
I'm currently on my thesis and therefore extremely busy, but I might actually do that afterwards ;)

**Comment by MaZderMind** [comment]
I'm sure @joto and I will help you out if you have questions then. Good Luck with your thesis.

**Comment by RockLobster** [comment]
Thank you :)

**Comment by mvexel** [comment]
@joto is this hard to do?

**Comment by joto** [comment]
@mvexel A few hours work. Not hard, but tedious. I know because I just did it. Result is here:
https://github.com/joto/osm-history-splitter

Not perfect, but it works. I switched the code to libosmium, did some C++11 modifications and other random cleanups. Behaves the same as before, some outputs messages are different. And there is no progress report any more. Libosmium doesn't have support for it (unlike the old Osmium) and it slowed down processing a lot anway (see #14). You need CMake now and the usual libosmium dependencies.

Everybody: Try this out and report any issues. Later we can think of bringing this back to this repository or maybe adding it to [osmium-tool](http://osmcode.org/osmium).

**Comment by MaZderMind** [comment]
I'd be happy to add a huge Link to the Frontpage pointing to jotos version, because I don't think I'll do much to it anyway in the future.
